[tool.poetry]
name = "lr4"
version = "0.1.0"
description = ""
authors = ["nikto_b <nikto_b@newt.team>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
